/**
 * Writes MARKERS.md: every file in the tree that carries a template marker,
 * with how many it carries, and the command that proves the template is
 * absorbed.
 *
 * @remarks
 * `bun run markers` rewrites the file. The gate's markers row runs the same
 * function and fails when the result differs from the index. `git grep` is
 * the reader, with `--untracked`, so a marker in a file not yet added counts
 * and a gitignored file does not. Every read and the write resolve against the
 * work tree's top, so the result is the same from any directory inside it.
 */

import { join } from 'node:path';
import { describe, run } from './run';

/** The generated inventory, relative to the work tree's top. */
export const INVENTORY = 'MARKERS.md';

/** The marker, assembled at run time so this file does not count itself. */
const MARKER = ['TODO', '(kickstart):'].join('');

/** The pathspec that keeps the inventory, which quotes the marker, out of its own count. */
const EXCLUDE = `:!${INVENTORY}`;

/**
 * The environment every git call in the gate runs under: the gate's own, with
 * every inherited `GIT_*` variable removed.
 *
 * @remarks
 * A git hook can export `GIT_DIR` and `GIT_INDEX_FILE`, and either points git
 * at a repository or an index other than the tree `-C` names. With them gone,
 * git finds the repository from the directory alone.
 */
export function gitEnv(): Readonly<Record<string, undefined>> {
  return Object.fromEntries(
    Object.keys(process.env)
      .filter((name) => /^GIT_/i.test(name))
      .map((name) => [name, undefined]),
  );
}

/**
 * The work tree's top directory.
 *
 * @throws When the current directory is not inside a work tree
 */
export async function topLevel(): Promise<string> {
  const finished = await run(['git', '-C', process.cwd(), 'rev-parse', '--show-toplevel'], gitEnv());
  const top = finished.stdout.trim();
  if (finished.exitCode !== 0 || top.length === 0) {
    throw new Error(`git rev-parse --show-toplevel ${describe(finished)}`);
  }
  return top;
}

/**
 * Every file carrying the marker, with how many markers it carries, sorted by
 * path.
 *
 * @throws When `git grep` fails for a reason other than finding nothing
 */
async function scan(top: string): Promise<ReadonlyMap<string, number>> {
  // -o prints every match on its own line, so two markers on one line count
  // twice. --text, because for a binary file git grep prints "Binary file
  // <path> matches" with no NUL, whatever -z says. --full-name keeps each
  // path relative to the top.
  const finished = await run(
    ['git', '-C', top, 'grep', '-z', '-o', '--text', '--full-name', '--untracked', '-F', MARKER, '--', '.', EXCLUDE],
    gitEnv(),
  );
  // git grep exits 1 when nothing matches, which is the absorbed tree.
  if (finished.exitCode === 1 && finished.stdout.length === 0) {
    return new Map();
  }
  if (finished.exitCode !== 0) {
    throw new Error(`git grep ${describe(finished)}`);
  }
  // -z ends each path with a NUL, so a path holding a colon still splits.
  const counts = new Map<string, number>();
  for (const line of finished.stdout.split('\n')) {
    if (line.length === 0) {
      continue;
    }
    const [path = ''] = line.split('\0');
    counts.set(path, (counts.get(path) ?? 0) + 1);
  }
  return new Map([...counts].sort(([a], [b]) => (a < b ? -1 : a > b ? 1 : 0)));
}

/** The inventory's text for the files `scan` found. */
function render(found: ReadonlyMap<string, number>): string {
  const total = [...found.values()].reduce((sum, count) => sum + count, 0);
  const lines = ['<!-- Auto-generated by scripts/markers.ts. Do not edit. -->', '', '# Template markers', ''];
  if (found.size === 0) {
    lines.push('No marker remains. The template is absorbed.');
    return `${lines.join('\n')}\n`;
  }
  lines.push(
    `${String(total)} ${total === 1 ? 'marker' : 'markers'} in ${String(found.size)} ${found.size === 1 ? 'file' : 'files'}, each a place a repository created from this template acts on.`,
    '',
    ...[...found].map(([path, count]) => `- \`${path}\`: ${String(count)}`),
    '',
    'The template is absorbed once this command exits 0:',
    '',
    '```sh',
    // Anchored at the top, because git grep given only an exclude pathspec
    // searches the current directory. Exit 1 alone reads as absorbed, because
    // git grep exits 128 on an error, such as a run from inside .git. The exit
    // is captured with ||, so the test decides the status. The subshell makes
    // the whole command one status, so under set -e, a workflow step's shell
    // included, any non-zero exit stops the script, a failed rev-parse too. The flags and pathspecs match scan(), so the command
    // and the inventory read the same files: --untracked skips what .gitignore
    // names, and a binary match still counts, because -q exits on any match.
    `( top=$(git rev-parse --show-toplevel) && { rc=0; git -C "$top" grep -q --untracked -F '${MARKER}' -- '${EXCLUDE}' || rc=$?; test "$rc" -eq 1; } )`,
    '```',
  );
  return `${lines.join('\n')}\n`;
}

/**
 * How many files {@link scan} reads: every tracked file and every untracked
 * one no ignore rule names, the inventory aside, through the same pathspecs.
 *
 * @throws When `git ls-files` fails
 */
async function searchedFiles(top: string): Promise<number> {
  const finished = await run(
    ['git', '-C', top, 'ls-files', '-z', '--cached', '--others', '--exclude-standard', '--', '.', EXCLUDE],
    gitEnv(),
  );
  if (finished.exitCode !== 0) {
    throw new Error(`git ls-files ${describe(finished)}`);
  }
  return new Set(finished.stdout.split('\0').filter((path) => path.length > 0)).size;
}

/**
 * Rewrites {@link INVENTORY} at the work tree's top from the whole tree.
 *
 * @returns How many files the scan read and how many markers it found
 */
export async function writeInventory(): Promise<{ readonly files: number; readonly markers: number }> {
  const top = await topLevel();
  const found = await scan(top);
  await Bun.write(join(top, INVENTORY), render(found));
  return { files: await searchedFiles(top), markers: [...found.values()].reduce((sum, count) => sum + count, 0) };
}

if (import.meta.main) {
  await writeInventory();
}
